[versions]
exposed = "0.60.0"
glowingentities = "1.4.3"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }

glowingentities = { module = "fr.skytasul:glowingentities", version.ref = "glowingentities" }

[bundles]
exposed = ["exposed-core", "exposed-jdbc", "exposed-dao"]